# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.8
        
    - name: Test
      run: go test -v ./...

    - name: Build tealsp win32/x64
      run: env GOOS=windows GOARCH=amd64 go build -o tealsp_win32_x64.exe cmd/tealsp/main.go

    - name: Build tealsp linux/x64
      run: env GOOS=linux GOARCH=amd64 go build -o tealsp_linux_x64 cmd/tealsp/main.go

    - name: Build tealsp darwin/x64
      run: env GOOS=darwin GOARCH=amd64 go build -o tealsp_darwin_x64 cmd/tealsp/main.go

    - name: Build tealsp darwin/arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o tealsp_darwin_arm64 cmd/tealsp/main.go
      
    - name: Build tealsarif linux/x64
      run: env GOOS=linux GOARCH=amd64 go build -o tealsarif_linux_x64 cmd/tealsarif/main.go
      
    - name: Prepare version file
      run: echo $GITHUB_SHA > version

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: dev
        artifacts: "tealsp_win32_x64.exe,tealsp_linux_x64,tealsp_darwin_x64,tealsp_darwin_arm64,tealsarif_linux_x64,version"
        prerelease: true
