# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Build tealsp windows/amd64
      run: env GOOS=windows GOARCH=amd64 go build -o .build/windows/amd64/tealsp.exe cmd/tealsp/main.go

    - name: Build tealsp linux/amd64
      run: env GOOS=linux GOARCH=amd64 go build -o .build/linux/amd64/tealsp cmd/tealsp/main.go

    - name: Build tealsp darwin/amd64
      run: env GOOS=darwin GOARCH=amd64 go build -o .build/darwin/amd64/tealsp cmd/tealsp/main.go

    - name: Build tealsp darwin/arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o .build/darwin/arm64/tealsp cmd/tealsp/main.go

    - name: Test
      run: go test -v ./...

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: dev
        artifacts: ".build/windows/amd64/tealsp.exe,.build/linux/amd64/tealsp,.build/darwin/amd64/tealsp,.build/darwin/arm64/tealsp"
        prerelease: true
